const jsonData = [
    { 
        sno: '1',
        name:"Jagadeesh",
        time:"05:40pm",
        from_city:"Gurgon",
        to_city:"Mumbai",
        v_type:"Truck",
        v_size:"20ft",
        v_body:"Close",
        v_loadingdata:"17/02/2024",
        remark:"Urgent Delivery",
        phone_number:"0123456789",
        target_price:"5000",
        no_of_bider_for_this_bid:"",
        expiry_date:"15/03/2024",
        load_point:"Ramchandra Ramniwas oil mill ,Alwar ,Rajasthan",
        unloading_point:"Ramchandra Ramniwas oil mill ,Alwar ,Rajasthan",
        no_of_vehicals:"1",
        staff_id:"51551311",
        bidnumber: '#1223456',
        startdata: '14/02/2024', 
        bidtime: '7hr 20min', 
        fromtocity: 'gurdan mumbai', 
        vehicaltype: 'Truck 20 ft', 
        materialweight: '400kg',
        material:"Agriculture products", 
        response: '4', 
        assgnedstaff: 'Mohit', 
        details: 'View Details' 
    },
    { 
        sno: '2',
        name:"Jagadeesh",
        time:"05:40pm",
        from_city:"Gurgon",
        to_city:"Mumbai",
        v_type:"Truck",
        v_size:"20ft",
        v_body:"Close",
        v_loadingdata:"17/02/2024",
        remark:"Urgent Delivery",
        phone_number:"0123456789",
        target_price:"5000",
        no_of_bider_for_this_bid:"",
        expiry_date:"15/03/2024",
        load_point:"Ramchandra Ramniwas oil mill ,Alwar ,Rajasthan",
        unloading_point:"Ramchandra Ramniwas oil mill ,Alwar ,Rajasthan",
        no_of_vehicals:"1",
        staff_id:"51551311",
        bidnumber: '#1223456',
        startdata: '14/02/2024', 
        bidtime: '7hr 20min', 
        fromtocity: 'gurdan mumbai', 
        vehicaltype: 'Truck 20 ft', 
        materialweight: '400kg',
        material:"Agriculture products", 
        response: '4', 
        assgnedstaff: 'Mohit', 
        details: 'View Details' 
    },
    { 
        sno: '3',
        name:"Jagadeesh",
        time:"05:40pm",
        from_city:"Gurgon",
        to_city:"Mumbai",
        v_type:"Truck",
        v_size:"20ft",
        v_body:"Close",
        v_loadingdata:"17/02/2024",
        remark:"Urgent Delivery",
        phone_number:"0123456789",
        target_price:"5000",
        no_of_bider_for_this_bid:"",
        expiry_date:"15/03/2024",
        load_point:"Ramchandra Ramniwas oil mill ,Alwar ,Rajasthan",
        unloading_point:"Ramchandra Ramniwas oil mill ,Alwar ,Rajasthan",
        no_of_vehicals:"1",
        staff_id:"51551311",
        bidnumber: '#1223456',
        startdata: '14/02/2024', 
        bidtime: '7hr 20min', 
        fromtocity: 'gurdan mumbai', 
        vehicaltype: 'Truck 20 ft', 
        materialweight: '400kg',
        material:"Agriculture products", 
        response: '4', 
        assgnedstaff: 'Mohit', 
        details: 'View Details' 
    },
    { 
        sno: '4',
        name:"Jagadeesh",
        time:"05:40pm",
        from_city:"Gurgon",
        to_city:"Mumbai",
        v_type:"Truck",
        v_size:"20ft",
        v_body:"Close",
        v_loadingdata:"17/02/2024",
        remark:"Urgent Delivery",
        phone_number:"0123456789",
        target_price:"5000",
        no_of_bider_for_this_bid:"",
        expiry_date:"15/03/2024",
        load_point:"Ramchandra Ramniwas oil mill ,Alwar ,Rajasthan",
        unloading_point:"Ramchandra Ramniwas oil mill ,Alwar ,Rajasthan",
        no_of_vehicals:"1",
        staff_id:"51551311",
        bidnumber: '#1223456',
        startdata: '14/02/2024', 
        bidtime: '7hr 20min', 
        fromtocity: 'gurdan mumbai', 
        vehicaltype: 'Truck 20 ft', 
        materialweight: '400kg',
        material:"Agriculture products", 
        response: '4', 
        assgnedstaff: 'Mohit', 
        details: 'View Details' 
    },
        
  ];

  export default jsonData